### PR TITLE
Support more devices

### PR DESCRIPTION
**Pull request by LukeShortCloud**
by adding udev rules to checking for virtual SATA/SCSI/USB devices, eMMC and SD cards, and NVMe drives.

### CODE REVIEW

**Comment by LukeShortCloud** [comment]
Successfully tested with: hotplugged SATA drive (sd\*), USB drive (sd\*),  virtual SATA drive (vd\*), and a microSD card (mmcblk\*p\*). I have a server with hot pluggable NVMe drives but I do not have any available slots to test with. However, I am successfully using these naming conventions (including NVMe) for my root file system resize script ii my winesapOS project: https://github.com/LukeShortCloud/winesapOS/blob/3.3.0/scripts/winesapos-resize-root-file-system.sh

**Comment by LukeShortCloud** [comment]
I finally got around to testing with NVMe. That works, too!

```
└─nvme1n1p2 259:8    0   1.7T  0 part /media/nvme1n1p2.ntfs
```

**Comment by Ferk** [comment]
Thank you!
Initially I was reluctant to add support for more devices, afraid of it potentially cause conflicts in some systems. But honestly I think it should be fine, specially since adding an entry in fstab would prevent it from being mounted anyway.

**Comment by LukeShortCloud** [comment]
Thanks for the info and context. If any major issues arise, I can help try to fix them or, worst-case, we could revert the patches. And thank you so much for your hard work creating this project!

**Pull request merged**
